Updates to call spots algorithm + viewer fixes
reillytilbury/coppafish pull request #324
Opened 2024-07-03 16:07 UTC by reillytilbury

### Checklist
- [ ] I have updated the `changelog.txt`, if applicable.
- [ ] I have bumped the software version in `_version.py`, if applicable.
- [ ] I have checked that the unit tests passed.
- [ ] I have checked that Minnie and/or RoboMinnie passed.
- [ ] I have resolved merge conflicts.

2024-07-04 08:17 UTC, paulshuker requested changes

2024-07-04 08:17 UTC, paulshuker commented on coppafish/plot/call_spots/test/test_parameter_estimation.py
This code is all commented out. This should be deleted if unwanted.

2024-07-04 08:18 UTC, paulshuker commented on coppafish/plot/call_spots/test/test_parameter_estimation.py
Other than that I happy with the changes.

2024-07-05 13:38 UTC, reillytilbury commented on coppafish/plot/call_spots/test/test_parameter_estimation.py
Yes these tests need to be rewritten as the functions now take the notebook as arguments. It is not an urgent change so I reccommend sending the changes through first

2024-07-05 14:11 UTC, merged